config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :donations do
  	resources :reservations, only: [ :index, :create, :edit, :update, :new ]
  	#resources :categories, only: [ :index, :show ]
  end

  resources  :reservations, only: [ :destroy ]
  resources :users, only: [ :show ]
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :donations, through: :donation_categories
end

app/models/donation.rb
class Donation < ApplicationRecord
  geocoded_by :address
  validates :address, presence: true
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many :donation_categories
  has_many :categories, through: :donation_categories
  has_one_attached :photo
end

app/models/donation_category.rb
class DonationCategory < ApplicationRecord
  belongs_to :category
  belongs_to :donation
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :donation
  belongs_to :visit
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :donations
  has_one_attached :photo
end

app/models/visit.rb
class Visit < ApplicationRecord
  has_many :donations, through: :reservations
  has_many :reservations, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :auth_visit
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:root, :index], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  def set_white_navbar
    @white_navbar = true
  end

  def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def auth_visit
    if Visit.find_by(token: cookies.encrypted[:token])
      @visit = Visit.find_by(token: cookies.encrypted[:token])
    else
      token = SecureRandom.hex(8)
      cookies.encrypted[:token] = token
      @visit = Visit.create(token: token)
    end
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:show, :index]
  before_action :set_white_navbar, only: [:index]
  before_action :set_donation, only: [:show, :edit, :update, :destroy]
  def index
    @donations = policy_scope(Donation).all
    @categories = Category.all
    if params[:categories].present?
      @donations = @donations.joins(:categories).where("categories.id =?", "#{params[:categories]}")
    end
    if params[:address].present?
      @donations= @donations.near(params[:address], 100)
    end
    if params[:query].present?
      sql_query = " \
        donations.name ILIKE :query \
        OR donations.description ILIKE :query \
        OR categories.name ILIKE :query \
      "
      @donations = @donations.joins(:categories).where(sql_query, query: "%#{params[:query]}%")
    end
    # while there is no reservation, donation is displayed.
    #@donations = policy_scope(Donation)
    #@donations = Donation.geocoded # returns donations with coordinates
    @markers = @donations.geocoded.map do |donation|
      {
        lat: donation.latitude,
        lng: donation.longitude
      }
    end
  end

  def create
    @donation = current_user.donations.create!(donation_params)
    if @donation.save
      redirect_to donations_path
    else
      render :new
    end
    authorize @donation
  end

  def show
    authorize @donation
  end

  def new
    @donation = Donation.new
    authorize @donation
  end

  def edit
    authorize @donation
  end

  def update
    @donation = Donation.find(params[:id])
    if @donation.update(donation_params)
      redirect_to @donation, notice: "Donation was succesfully updated."
    else
      render :edit
    end
  end

  def destroy
    @donation.destroy
    redirect_to user_path(:id), notice: "Donation was succesfully deleted."
  end

  private

  def set_donation
    @donation = Donation.find(params[:id])
    authorize @donation
  end

  def donation_params
    params.require(:donation).permit(:name, :address, :description, :longitude, :latitude, :timeframe, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @categories = Category.all
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @reservations = policy_scope(Reservation).where(visit: @visit)

    @donations = @reservations.map do |reservation|
      reservation.donation
    end.uniq

      @markers = @donations.map do |donation|
      {
        lat: donation.latitude,
        lng: donation.longitude
      }
    end
  end

  def new

    @donation = Donation.new
    @reservation = Reservation.new
    authorize @reservation

  end

  def create
    @donation = Donation.find(params[:donation_id])
    @reservation = Reservation.new
    @reservation.donation = @donation
    @reservation.visit = @visit
    @reservation.status = "Reserved"

    if @reservation.save
      redirect_to donation_reservations_path(@donation)
    else
      render :new
    end
    authorize @reservation
  end

  def show
  	@donation = Donation.find(params[:donation_id])
  	@reservation = Reservation.find(params[:id])
  	@reservation = @donation.reservation
  end

  def update
  	@donation = Donation.find(params[:donation_id])
  	@reservation = Reservation.find(params[:id])
  	@reservation.status = "Reserved"
    @reservation.save!
    # ?? Change to ""
    redirect_to donation_path(@donation)
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to root_path
  end

  #private

  # def reservation_params
  #   params.require(:reservation).permit(:status)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_white_navbar, only: [:show]
  
  def index
  @users = User.geocoded # returns users (organizations) with coordinates
  @markers = @users.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude
      }
    end
  end

  def show
    @user = current_user
    authorize @user
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  
  def new
    if cookies.encrypted[:token].present?
      redirect_to donations_path
    else
      @visit = Visit.new
    end
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/donations/_info_window.html.erb
<h2><%= donation.name %></h2>
<p><%= donation.address %></p>

app/views/donations/edit.html.erb
<% content_for :meta_title, "Update #{@donation.name} on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @donation.description %>
<% content_for :meta_image, cl_image_path(@donation.photo.key) %>
<div class="container">
      <div class="card-home">
        <div class="form_group">
          <%= simple_form_for @donation do |f| %>

          <%= f.input :name,  prompt: "Name" %>

          <%= f.input :address, prompt: "Address" %>

          <%= f.input :description, prompt: "Description" %>

          <%= f.input :timeframe, prompt: "Details"%>

          <%= f.input :photo, as: :file, input_html: { multiple: false } %>

          <%= f.button :submit, "Update donation", class: "btn-primary" %>

          <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>

          <% end %>
          <br>
        </div>
      </div>
</div>

app/views/donations/index.html.erb
<% content_for :meta_title, "Donations on #{DEFAULT_META["meta_product_name"]}" %>
<div class="container index">
  <div class="header-decoration">
    <%= image_tag "index_background_element.png", alt: "decoration element black form" %>
  </div>
    <button class="map-btn button-filled toggle">SHOW MAP</button>
      <div class="home-searchform-filter">
        <%= form_with(url: donations_path, method: "get", html: { class: "form-inline"}) do |f| %>
        <%= f.collection_select(:categories, @categories, :id, :name, {}, { onchange: "this.form.submit()" }) %>
        <% end %>
      </div>
      <div class="map toggle-hidden" id="map"
        style="width: 90vw; height: 100vh;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        <p style="text-align: justify; color: #3a3a3a"><strong>Important: </strong><br>Please make sure, the meeting is arranged in a public area.</p>
      </div>
      <div class="list">
        <% @donations.each do |donation| %>
          <div class= "list-item">
          <span class="list-item-trigger"><%= donation.name %></span>
          <%= cl_image_tag donation.photo.key, class: "list-item-pic" %>
          <%= link_to donation_path(donation), class: "list-item-link" do %>
          <span><%= donation.name %></span>
          <div class="icon">
            <i class="fas fa-plus"></i>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/donations/new.html.erb
<% content_for :meta_title, "Add a donation on #{DEFAULT_META["meta_product_name"]}" %>
<div class="container new">
  <div id="new-header-decoration">
    <%= image_tag "new_header_element.png", alt: "Header element add donation page" %>
  </div>
    <h2>Add your donation</h2>
  <div class="new-searchform">
    <%= simple_form_for @donation, class: 'from-inline new' do |f| %>
    <%= f.input :name,  placeholder: 'Name the item',label:false, class: 'from-inline new' %>
    <%= f.input :address, placeholder: "Where do you want to meet?", label:false %>
    <%= f.input :description, placeholder: "Describe the article", label:false %>
    <%= f.input :timeframe, placeholder: "What time? Any other details?", label:false %>
    <%= f.input :photo, as: :file, input_html: { multiple: false }, label:false %>
    <%= f.button :submit, "ADD DONATION", class: "button-filled create" %>
    <% end %>
  </div>
    <div id="new-footer-decoration">
      <%= image_tag "new_footer_element.png", alt: "Footer element add donation page" %>
    </div>
</div>

app/views/donations/show.html.erb
<% content_for :meta_title, "#{@donation.name} on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @donation.description %>
<% content_for :meta_image, cl_image_path(@donation.photo.key) %>
<div class="container show">
  <div class="show-image">
    <%= cl_image_tag @donation.photo.key, id:"show-banner" %>
  </div>
  <div>
    <%= image_tag "show_background_element_left.png", id: "show-decoration-left", alt: "decoration element yellow" %>
  </div>
  <div class="show-details">
    <div id="info-name">
      <h1><%= @donation.name %></h1>
      <h3>Donated by:<br><%= @donation.user.user_name.split.map(&:capitalize).join(' ') %></h3>
    </div>
    <div id="info-description">
      <p><%= @donation.description %></p>
      <p>This resource can be accessed at: <%= @donation.address %>.</p>
      <% if @donation.user.private == true %>
        <p>Appointment: <br><%= @donation.timeframe %>, <%= @donation.updated_at.strftime("%A %e %B %Y") %></p>
      <% else %>
        <p>Appointment: <%= @donation.timeframe %></p>
      <% end %>
      </p>
    </div>
    <div id="show-buttons">
      <%= link_to 'RESERVE', donation_reservations_path(@donation), class: "button-filled black", action: :create, method: :post %>
      <%= link_to 'BACK TO RESULTS', donations_path, class: "button-filled outline" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= csrf_meta_tags %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <%= favicon_link_tag asset_path('ourhub-favicon.png') %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Homeless? Find resources in your local area. Have spare items? Offer them to people in need.">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.2.0/mapbox-gl-geocoder.min.js'></script>
    <link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.2.0/mapbox-gl-geocoder.css' type='text/css' />

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-home">
  <div class="banner">
    <%= image_tag "home_banner_main.jpg", alt: "Image landing page" %>
  </div>
  <div class="home-searchform">
    <%= form_tag donations_path, method: 'GET', html: { class: 'form-inline' } do %>
      <%= label_tag :query do %>
      <%end%>
      <%= text_field_tag :query,
      params[:query],
      class: "form-inline",
      placeholder: "What are you looking for?"
      %>
      <%= text_field_tag :address,
      params[:address],
      class: "form-inline",
      placeholder: "Approximate location"
      %>
      <%= submit_tag "SEARCH", class: "button-filled-search" %>
      <%= submit_tag "SHOW ALL", class: "button-filled-list-all" %>
    <% end %>
  </div>
  <div class="card-home">
    <h2>Help homeless in your <br>neighbourhood</h2>
      <p>You have some spare clothes or equipment that are still in good condition?
        Or you prepared too much food for an event? <br><br>You could be connected with a person in need, directly in your community.
      </p>
    </div>
    <div id="homepage-btn">
      <%= link_to "ADD DONATION", new_donation_path, class: "button-filled-add" %>
    </div>
    <div class="card-home">
      <h2>Among people.<br>Homeless people<br>and their stories</h2>
        <p>There are nearly 2000 people in Berlin currently without a home.
          With the support of homeless organisations and the local community, they've achieved amazing things and overcome some huge obstacles. <br>
          <br>Here are some of the real stories of Berlin's homeless and volunteers.
        </p>
    </div>
    <div id="homepage-btn">
      <%= link_to "STORIES", new_donation_path, class: "button-filled-stories" %>
    </div>
      <div class="footer-element">
    <%= image_tag "home_footer_element.jpg", alt: "Footer element home page" %>
      </div>
    </div>
</div>

app/views/pages/index.html.erb
<li>
  <%= @donations.each do |donation| %>
    <%= if policy(donation).show? %>
      <%= link_to 'Show', donation %>
    <%= end %>
  <%= end %>
</li>
<li>
  <%= @donations.each do |donation| %>
    <%= if policy(donation).update? %>
      <%= link_to 'Edit', edit_donation_path(donation) %>
    <%= end %>
  <%= end %>
</li>
<li>
  <%= @donations.each do |donation| %>
    <%= if policy(donation).destroy? %>
      <%= link_to 'Destroy', donation, method: :delete data: { confirm: Are you sure to delete your donation? } %>
    <%= end %>
  <%= end %>
</li>

app/views/pages/map.html.erb
map.html.erb

app/views/reservations/index.html.erb
<% content_for :meta_title, "Your reservations on #{DEFAULT_META["meta_product_name"]}" %>

  <div class="res-container">
    <div id="map" class="map res"
      style="width: 90%; height: 300px; align-items: center;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">


    </div>
    <div class="res-container">
       <div id="map-dl-btn">
        <%= link_to "DOWNLOAD", asset_path('Our Hub Resources.pdf'), :download => 'filename', class: "button-filled-add" %>
      </div>
    </div>



  <div class="res-container">
    <div class="res-list">

    <% if @visit.reservations[0].nil? %>
    <div class="alert alert-warning">
      <p>You have not reserved anything yet.</p>
    </div>
  <% else %>
  <% @visit.reservations.each do |reservation| %>
      <div class="res-image"><%= cl_image_tag reservation.donation.photo.key, height: 200, class: "align-self-center", id: "show-banner" %></div>
          
      <div class="res-details">
          <div id="res-info-description">
            <p><strong>Resource: </strong><%= reservation.donation.name %></p>
          </div>
          <div id="res-info-description">
            <p><strong>Location: </strong><%= reservation.donation.address %></p>
          </div>
          <div id="res-info-description">
            <p><strong>Details: </strong><%= reservation.donation.timeframe %></p>
           </div>
          <div id="res-info-description"> 
            <p><strong>By: </strong><%= reservation.donation.user.user_name %></p>
          </div>
        </div>
    <% end %>
<% end %>
</div>
</div>
</div>       
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="container-nav <%= 'white-navbar' if @white_navbar.present?%>">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <h1>Our Hub.</h1>
        <% end %>
      <!-- markup for the hamburger menu. Hamburger buns and stuffing (:^) are created with span elements  -->
      <div class="navbar-header">
        <div class="toggle-button" id="toggle">
          <span class="bar top"></span>
          <span class="bar bottom"></span>
        </div>
      </div>
    <!-- markup for the overlay -->
    <nav class="overlay" id="overlay">
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li>
          <% if user_signed_in? %>
            <%= link_to 'Your Profile', user_path(current_user) %>
          <% end %>
          </li>
        <li><a href="#">Stories</a></li>
        <li><a href="#">Contact</a></li>
        <li>
          <% if user_signed_in? %>
          <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
            <% end %>
          </li>
        <li>
          <% if user_signed_in? == false %>
          <%= link_to 'Login', new_user_session_path %>
            <% end %>
          </li>
      </ul>
    </nav>
  </div>
</div>

app/views/users/show.html.erb
<% content_for :meta_title, "#{@user.user_name.capitalize!}'s profile on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_image, cl_image_path(@user.photo.key) %>
<div class="container">
  <div class="header-decoration">
    <%= image_tag "dashboard_background_element.png", alt: "decoration element black form" %>
  </div>
  <div class="user-add" id="homepage-btn">
    <%= link_to "ADD DONATION", new_donation_path, class: "button-filled-add" %>
  </div>
  <div id="dashboard-headline">
    <h2>Your active donations</h2>
  </div>
  <div class="list-user">
    <ul>
      <% @user.donations.each do |donation| %>
        <div class="list-item-user">
          <li><%= link_to donation.name, donation_path(donation), class: "list-item-link" %></li>
          <div class="icons-user">
            <li><%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_donation_path(donation), class: "list-item-edit" %></li>
            <li><%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, donation_path(donation), class: "list-item-delete", method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </div>
          <% end %>
        </div>
    </ul>
  </div>
  <div id="dashboard-headline-reservations">
    <h2>Reserved items</h2>
  </div>
    <div class="list-user-res">
    <ul>
     
        <div class="list-item-user-res">
          <li class="list-item-link"> Men's Sweatshirt</li>
        </div>
        <div class="list-item-user-res">
          <li class="list-item-link"> Waterproof Jacket</li>
        </div>
        <div class="list-item-user-res">
          <li class="list-item-link"> First Aid Kit</li>
        </div>
    </ul>
  </div>

</div>

app/views/users/test.html.erb
  <div class="list-user">
    <ul>
     
        <div class="list-item-user">
          <li class: "list-item-link"> Men's sweatshirt</li>
        </div>
    </ul>
  </div>

app/views/visits/create.html.erb
<h1>Visits#create</h1>
<p>Find me in app/views/visits/create.html.erb</p>

app/views/visits/destroy.html.erb
<h1>Visits#destroy</h1>
<p>Find me in app/views/visits/destroy.html.erb</p>

app/views/visits/new.html.erb
<h1>Visits#new</h1>
<p>Find me in app/views/visits/new.html.erb</p>